<?php

namespace Database\Seeders;

use App\Models\SchoolClass;
use App\Models\Student;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

/**
 * RealStudentsSeeder
 *
 * Seeding data siswa riil SMKN 6 Jakarta berdasarkan dokumen nominasi kelas.
 * - Siswa Kelas X dinaikkan menjadi Kelas XI (9 kelas, 322 siswa)
 * - Siswa Kelas XI dinaikkan menjadi Kelas XII (9 kelas, 324 siswa)
 * Total: 646 siswa
 * Password default: Rahasia6# (didukung fallback: password)
 */
class RealStudentsSeeder extends Seeder
{
    public function run(): void
    {
        $classMap = SchoolClass::pluck('id', 'name')->toArray();
        $password = Hash::make('Rahasia6#');

        $students = [
            ['nis' => '20570', 'name' => 'ACHMAD RIDHO ISKANDARSYAH', 'gender' => 'L', 'class' => 'XI MP'],
            ['nis' => '20571', 'name' => 'ADINDA KIRANI PUSPA DEWI', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20578', 'name' => 'AKHMAL MUHAMMAD HUSEIN', 'gender' => 'L', 'class' => 'XI MP'],
            ['nis' => '20591', 'name' => 'ANDIETA SABRINA', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20600', 'name' => 'ARKANA SYAHLA SARASWATY AGUNG', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20605', 'name' => 'AURA CAHAYA NABILA', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20624', 'name' => 'CANTIKA PUTRI RAMADHAN', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20631', 'name' => 'CLAUDYA RIEUKA NABILQISTI', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20645', 'name' => 'DZAKIRAH DZATIL KAROMAH', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20662', 'name' => 'FAYRA ZHAAFIRA WIJAYA', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20664', 'name' => 'FIRA MUTHASYAM IDIWIJAYA', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20665', 'name' => 'FITRI ERMIYATI', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20689', 'name' => 'JASMINE CANTIKA FITRIANA', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20697', 'name' => 'KARMILA', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20698', 'name' => 'KAYLA FRIDASELLY', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20699', 'name' => 'KEISYA ASSYURA SAPUTRI', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20703', 'name' => 'KHADIJAH', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20715', 'name' => 'LUCIOLA NYAWA DALLIMA', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20720', 'name' => 'MANDA AMELIA PUTRI', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20725', 'name' => 'MAYLANI AURA PUTRI', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20733', 'name' => 'MONICA VIRIAL NABILA', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20745', 'name' => 'MUHAMMAD AL FATH NUR HIDAYAT', 'gender' => 'L', 'class' => 'XI MP'],
            ['nis' => '20749', 'name' => 'MUHAMMAD ATTAR MULYA', 'gender' => 'L', 'class' => 'XI MP'],
            ['nis' => '20758', 'name' => 'MUHAMMAD FIRMANSYAH', 'gender' => 'L', 'class' => 'XI MP'],
            ['nis' => '20789', 'name' => 'NAZWA JUNIAR', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20791', 'name' => 'NIA SULISTIANTI', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20799', 'name' => 'OCTORI PRATIWI', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20802', 'name' => 'PUTRI SOFIA ANANDITTA SOLEMAN', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20811', 'name' => 'RAHAYU INDAH', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20826', 'name' => 'RIDHO MAULANA', 'gender' => 'L', 'class' => 'XI MP'],
            ['nis' => '20836', 'name' => 'SAHARA NAILA PUTRI', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20841', 'name' => 'SALWAA SALSABILA', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20855', 'name' => 'SITI NUR ARR RAHMAN', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20860', 'name' => 'SYAFA ANGGITA LUTHFIANA', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20867', 'name' => 'TARA JASMIN VIANDHITA', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20879', 'name' => 'YULIANA SAFITRI', 'gender' => 'P', 'class' => 'XI MP'],
            ['nis' => '20573', 'name' => 'ADINDA PUTRI DHARMAWAN', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20575', 'name' => 'AHLAKUL KARIMAH AMIN', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20587', 'name' => 'AMIRA SAPITRI', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20588', 'name' => 'AMRINA RASYADA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20599', 'name' => 'ARIES MAULANA', 'gender' => 'L', 'class' => 'XI AK 1'],
            ['nis' => '20610', 'name' => 'AYU DIVYA RAHMA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20619', 'name' => 'BILQISTI ZULAIKHA RAHMADA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20630', 'name' => 'CLARISSA DIVELIA RADINKA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20647', 'name' => 'ELSY DWI YANTI', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20650', 'name' => 'FAHRI SUTANSYAH', 'gender' => 'L', 'class' => 'XI AK 1'],
            ['nis' => '20670', 'name' => 'GISELA TANIA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20671', 'name' => 'GISYA FARIDA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20676', 'name' => 'HANI NADA SALSABILA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20692', 'name' => 'JIHAN ALITA WIJAYA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20696', 'name' => 'KARENNINA NEFFA SHEVANIA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20707', 'name' => 'KINANTI VERLITA RIADI', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20710', 'name' => 'KUINSILA PUTRI FALISHA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20726', 'name' => 'MEILINA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20730', 'name' => 'MIFTAHU SURUR AL HAFIZH', 'gender' => 'L', 'class' => 'XI AK 1'],
            ['nis' => '20744', 'name' => 'MUHAMMAD AKHDAN NUGRAHA', 'gender' => 'L', 'class' => 'XI AK 1'],
            ['nis' => '20752', 'name' => 'MUHAMMAD AZWAR', 'gender' => 'L', 'class' => 'XI AK 1'],
            ['nis' => '20794', 'name' => 'NINDA AYU CAYARINI', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20806', 'name' => 'QULTUM NOVIYANI', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20808', 'name' => 'RADITYA DZAKI RAHMAN', 'gender' => 'L', 'class' => 'XI AK 1'],
            ['nis' => '20819', 'name' => 'RATU FELLYCTA WIBOWO', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20820', 'name' => 'RAYA ALKALIFI AQILA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20837', 'name' => 'SAHIDNA ANANDITA PRATIWI', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20840', 'name' => 'SALSABILA NADYA PUTRI', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20848', 'name' => 'SESYLIA DWI WAHYU MAHARANY', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20856', 'name' => 'SITI NUROHMAH', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20869', 'name' => 'VARIE AZAHRA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20870', 'name' => 'VIDI OKTAVIANO', 'gender' => 'L', 'class' => 'XI AK 1'],
            ['nis' => '20876', 'name' => 'WIRAETNY NARRA SUHENDRA', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20877', 'name' => 'YASMIN NUR AZIZAH', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20882', 'name' => 'ZAHRA AFRIANISA PUTRI', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20884', 'name' => 'ZARA DWI RAMADANI', 'gender' => 'P', 'class' => 'XI AK 1'],
            ['nis' => '20586', 'name' => 'ALZENA MALIKA RAHMA', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20593', 'name' => 'ANGGUN NADIFA FATHIN', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20601', 'name' => 'ARYA DAMAR SYANDANA', 'gender' => 'L', 'class' => 'XI AK 2'],
            ['nis' => '20607', 'name' => 'AURA SABILA OKTAVIANNI', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20614', 'name' => 'AZRA RAIDAH', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20632', 'name' => 'DARISAH TASKIYYAH', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20643', 'name' => 'DWITYA ATSILAH KHAIRINNISWAH', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20654', 'name' => 'FAREL DWI NUR RACHMAN', 'gender' => 'L', 'class' => 'XI AK 2'],
            ['nis' => '20655', 'name' => 'FARICA AZKA LAREINA', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20657', 'name' => 'FATHIMAH AAQILAH NURULRIZQI RIZALDA', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20672', 'name' => 'GLADYS MAURA LESMANA', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20677', 'name' => 'HANIFAH AFLAH AZIZAH', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20679', 'name' => 'HASNA SAFIA GUNAWAN', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20688', 'name' => 'ISNAYAH PUTRI', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20690', 'name' => 'JATI RAHAYU', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20705', 'name' => 'KHANSA NAYLA AZKIA', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20706', 'name' => 'KHUMAIRA LABIB SYAKIRA', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20728', 'name' => 'MEYLITSNA WIDYANDRA', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20740', 'name' => 'MUHAMAD NASTAIN AL FITRA', 'gender' => 'L', 'class' => 'XI AK 2'],
            ['nis' => '20746', 'name' => 'MUHAMMAD ALIF ADRIN RUFFI', 'gender' => 'L', 'class' => 'XI AK 2'],
            ['nis' => '20755', 'name' => 'MUHAMMAD FACHRI JULIAN', 'gender' => 'L', 'class' => 'XI AK 2'],
            ['nis' => '20772', 'name' => 'NABELLA CAHAYA', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20775', 'name' => 'NADIEN HAYA ODORA', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20795', 'name' => 'NOVA ALILA MUTHMAINAH', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20800', 'name' => 'OKTAVIA AGUSTINA RAMADHANI', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20803', 'name' => 'PUTRI ZAHRATUL AWAL', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20814', 'name' => 'RAIYSAH HAMIM', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20816', 'name' => 'RASYA REZKY ADITYA', 'gender' => 'L', 'class' => 'XI AK 2'],
            ['nis' => '20822', 'name' => 'RAYYA RIWANTI AULIA', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20838', 'name' => 'SALITA ZILDJIAND DWI PUTRI JARUMARI', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20845', 'name' => 'SEGARA PUTRA WARDANA', 'gender' => 'L', 'class' => 'XI AK 2'],
            ['nis' => '20852', 'name' => 'SILVI MAULINA', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20854', 'name' => 'SITI KHAERUN NAZAH', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20868', 'name' => 'TIARA SALSABILLA PUTRI HENINDYA', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20872', 'name' => 'VIVI HIDAYATI', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20883', 'name' => 'ZAHRA KUSUMA WARDANI', 'gender' => 'P', 'class' => 'XI AK 2'],
            ['nis' => '20576', 'name' => 'AJENG DEVINA MUTIYASARI', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20579', 'name' => 'ALFATH RIZKY', 'gender' => 'L', 'class' => 'XI BR 1'],
            ['nis' => '20581', 'name' => 'ALIYA NISA', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20616', 'name' => 'AZZRA PUTRI MUARIFFAH', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20627', 'name' => 'CHIKA PUTRI UMAYRA', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20634', 'name' => 'DEASTALIA SRI SUGIANTI', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20644', 'name' => 'DZAKIRA TALITA ZAHRA RAMADHANI', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20653', 'name' => 'FAJAR RADITYA', 'gender' => 'L', 'class' => 'XI BR 1'],
            ['nis' => '20660', 'name' => 'FATIMAH NURUDZ ZAHRA', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20678', 'name' => 'HANNIFAH JELITA RIZKI', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20680', 'name' => 'HASNALINA MAZAYARIZQA SA\'DAN', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20687', 'name' => 'IRSA WINADIN', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20713', 'name' => 'LIRA VIRA NISA', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20714', 'name' => 'LUCIANA', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20731', 'name' => 'MILA DIAH NUR', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20732', 'name' => 'MOH. ALIF', 'gender' => 'L', 'class' => 'XI BR 1'],
            ['nis' => '20734', 'name' => 'MOUZA RIN JANIE PUTRI MAULANA', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20735', 'name' => 'MUHAMAD ANDRE', 'gender' => 'L', 'class' => 'XI BR 1'],
            ['nis' => '20737', 'name' => 'MUHAMAD FACHRI', 'gender' => 'L', 'class' => 'XI BR 1'],
            ['nis' => '20757', 'name' => 'MUHAMMAD FIGO ZAHRIAN', 'gender' => 'L', 'class' => 'XI BR 1'],
            ['nis' => '20759', 'name' => 'MUHAMMAD FURQAN HAIDAR', 'gender' => 'L', 'class' => 'XI BR 1'],
            ['nis' => '20766', 'name' => 'MUHAMMAD RIZKI KHADAFI', 'gender' => 'L', 'class' => 'XI BR 1'],
            ['nis' => '20768', 'name' => 'MUHAMMAD ZAINI ILHAM', 'gender' => 'L', 'class' => 'XI BR 1'],
            ['nis' => '20774', 'name' => 'NADIA AMANDA YULIANTI', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20797', 'name' => 'OCTAVIANI CHELSEA GUNAWAN', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20804', 'name' => 'QANITA ZHAFIRA PUTRI CANDRASA', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20813', 'name' => 'RAISYA KANIA PUTRI SUSILO', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20835', 'name' => 'SABILLAH PUTRI MANDIYATA', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20842', 'name' => 'SASKIA ALIKA PUTRI', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20843', 'name' => 'SATRIA RIZKY NUGROHO PUTRA', 'gender' => 'L', 'class' => 'XI BR 1'],
            ['nis' => '20847', 'name' => 'SELVI KARLINA', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20857', 'name' => 'SITI SALMAH', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20862', 'name' => 'SYAFFA\'ATUS SHOLEHA', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20864', 'name' => 'SYA\'ID AGHIL THAHER', 'gender' => 'L', 'class' => 'XI BR 1'],
            ['nis' => '20865', 'name' => 'SYAIKA FATHIA', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20881', 'name' => 'ZAHIRAH MAHARANI', 'gender' => 'P', 'class' => 'XI BR 1'],
            ['nis' => '20569', 'name' => 'A\'AM AMALIA ZAHRO', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20585', 'name' => 'ALSA AMANDA', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20594', 'name' => 'ANGGUN SHAFITRI OCTAVIA', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20602', 'name' => 'ASTRI JUANITA', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20603', 'name' => 'ASYAVIRA JAMILAH ARABIAN', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20611', 'name' => 'AZ ZAHRA SITA ZAILANI', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20626', 'name' => 'CHAYARA MALIQAH TILLOTAMA', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20628', 'name' => 'CIKA ARYA AZ ZAHRA', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20636', 'name' => 'DEVIN AL SHABRI', 'gender' => 'L', 'class' => 'XI BR 2'],
            ['nis' => '20639', 'name' => 'DHARMA PRANAYA', 'gender' => 'L', 'class' => 'XI BR 2'],
            ['nis' => '20641', 'name' => 'DIRA SETIANINGSIH', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20656', 'name' => 'FATHAN KHOIRI ASSHIDQI', 'gender' => 'L', 'class' => 'XI BR 2'],
            ['nis' => '20684', 'name' => 'IBNU FADILAH', 'gender' => 'L', 'class' => 'XI BR 2'],
            ['nis' => '20691', 'name' => 'JIHAAN ALIFA', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20702', 'name' => 'KEYVI KHAIRUNNISA NOVRI', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20716', 'name' => 'M. REHAN', 'gender' => 'L', 'class' => 'XI BR 2'],
            ['nis' => '20717', 'name' => 'MADELINE NATALIA GULO', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20723', 'name' => 'MARSYA ASHIILAH VAN ROO', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20741', 'name' => 'MUHAMAD RIDHO DERMAWAN', 'gender' => 'L', 'class' => 'XI BR 2'],
            ['nis' => '20770', 'name' => 'MUTHIA ADIBA', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20779', 'name' => 'NAOMI KINANTA RAMADHANI', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20782', 'name' => 'NATHANAEL ANDRA ADITHYA', 'gender' => 'L', 'class' => 'XI BR 2'],
            ['nis' => '20783', 'name' => 'NAUFAL LUTHFY RACHMANTO', 'gender' => 'L', 'class' => 'XI BR 2'],
            ['nis' => '20785', 'name' => 'NAURA NADZIFAH KHUZAIMAH', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20805', 'name' => 'QUEENSHA SAGIFA', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20810', 'name' => 'RAFFA AKBAR RAHMADAN', 'gender' => 'L', 'class' => 'XI BR 2'],
            ['nis' => '20824', 'name' => 'RIADHATUL AINI', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20829', 'name' => 'RIFAT FAKHRIAN NURIADI', 'gender' => 'L', 'class' => 'XI BR 2'],
            ['nis' => '20830', 'name' => 'RISMA FEBRIANTI', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20831', 'name' => 'RIZKA ANAS TASYA', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20834', 'name' => 'RYO AKBAR JULIANTO', 'gender' => 'L', 'class' => 'XI BR 2'],
            ['nis' => '20851', 'name' => 'SIFIYA ANGGRAINI', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20853', 'name' => 'SITI AINUL MARDIAH', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20863', 'name' => 'SYAHRIZAD RAFIDAH AZIZ', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20875', 'name' => 'WINSHA AIRA PRAMESTY', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20890', 'name' => 'ZIVANNA MULIA', 'gender' => 'P', 'class' => 'XI BR 2'],
            ['nis' => '20574', 'name' => 'ADRIELL MATTHEW DANIELO MATAKENA', 'gender' => 'L', 'class' => 'XI DKV 1'],
            ['nis' => '20577', 'name' => 'AKBAR ADI NUGROHO', 'gender' => 'L', 'class' => 'XI DKV 1'],
            ['nis' => '20583', 'name' => 'ALMAIRA JINGGA NARASNAMA', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20592', 'name' => 'ANGGIA LILAH HASIHOLAN', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20598', 'name' => 'AQILA NATASYA', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20623', 'name' => 'CAHAYA HIKARU', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20625', 'name' => 'CARLENE AZALEA HIDAYADI', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20633', 'name' => 'DEAN TIRTA MAULANA', 'gender' => 'L', 'class' => 'XI DKV 1'],
            ['nis' => '20637', 'name' => 'DEVINA FARHANI', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20640', 'name' => 'DIDA JAUZAAN', 'gender' => 'L', 'class' => 'XI DKV 1'],
            ['nis' => '20648', 'name' => 'EVANS EMERALDY YULIANTO', 'gender' => 'L', 'class' => 'XI DKV 1'],
            ['nis' => '20659', 'name' => 'FATIMAH AZZAHRA', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20666', 'name' => 'FITRIANA AULIA AZZAHRA', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20694', 'name' => 'KALEA MIRABEL LAERINA PUTRI GAUTAMA', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20695', 'name' => 'KANAYA RAMADHANI', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20711', 'name' => 'LETISYA PUTRI DWI BASTIANTI', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20712', 'name' => 'LINTANG SURYA WIJAYA', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20718', 'name' => 'MALIKA ALYA SALSABILA', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20729', 'name' => 'MICHELLE NOV MUTIARA AZALIA ANHWA', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20754', 'name' => 'MUHAMMAD DZIBRAN', 'gender' => 'L', 'class' => 'XI DKV 1'],
            ['nis' => '20756', 'name' => 'MUHAMMAD FAJAR GEMILANG', 'gender' => 'L', 'class' => 'XI DKV 1'],
            ['nis' => '20765', 'name' => 'MUHAMMAD RIZA RAMADHAN', 'gender' => 'L', 'class' => 'XI DKV 1'],
            ['nis' => '20771', 'name' => 'MYISHA SAKHI RAHADATUL AISY', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20777', 'name' => 'NAISYA TIARA PUTRI', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20787', 'name' => 'NAYLA DZIHNI SHABRIYA', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20798', 'name' => 'OCTHAVIANI ADE PUTRI', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20815', 'name' => 'RAMEYZA ALIYA SAEEDA', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20823', 'name' => 'REIHANA SAFA MAGFIROH', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20825', 'name' => 'RIDHO AKBAR SHOLIHIN', 'gender' => 'L', 'class' => 'XI DKV 1'],
            ['nis' => '20846', 'name' => 'SELLA NUR AZIZAH', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20850', 'name' => 'SHEILA PUTRI YUWONO', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20859', 'name' => 'SULTHAN ALFANSYAH', 'gender' => 'L', 'class' => 'XI DKV 1'],
            ['nis' => '20874', 'name' => 'WINDA WAHYA HITHOH', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20880', 'name' => 'ZAFIRA PUTRI RAYYANI', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20888', 'name' => 'ZHAFIRA ALTHAFUNNISA', 'gender' => 'P', 'class' => 'XI DKV 1'],
            ['nis' => '20572', 'name' => 'ADINDA NADIAH WADINI', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20580', 'name' => 'ALIFA AL FATHUNISA\'', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20590', 'name' => 'ANDI ZAKIA SALMA MAKMUR', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20604', 'name' => 'AUBREY RANA ALEEZA', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20609', 'name' => 'AYRA KANAYA VILANY', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20613', 'name' => 'AZMIA ZAHRA', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20621', 'name' => 'BUNGA SABRINA', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20629', 'name' => 'CINTA SALSABILA AULIA ZAHRA', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20642', 'name' => 'DUNCAN SYAWA RYAN GIGS', 'gender' => 'L', 'class' => 'XI DKV 2'],
            ['nis' => '20658', 'name' => 'FATHMA TRYA ARIMBI SUSANTO', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20663', 'name' => 'FIKRI AL AWAL', 'gender' => 'L', 'class' => 'XI DKV 2'],
            ['nis' => '20674', 'name' => 'HAERUNIS YURI', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20675', 'name' => 'HAIKAL HAKIKI', 'gender' => 'L', 'class' => 'XI DKV 2'],
            ['nis' => '20681', 'name' => 'HAURA NISRINA', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20682', 'name' => 'HAWA NIDA KARIMAH', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20686', 'name' => 'INTAN FADILA MUTIARA SRI UTAMI', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20701', 'name' => 'KEVIN AL BAZIDI', 'gender' => 'L', 'class' => 'XI DKV 2'],
            ['nis' => '20721', 'name' => 'MARDYAS SEKAR PEMBAYUN', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20727', 'name' => 'MERLY NAZLYANI PUTRI', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20751', 'name' => 'MUHAMMAD AZKARAVA VITO PRADANA', 'gender' => 'L', 'class' => 'XI DKV 2'],
            ['nis' => '20761', 'name' => 'MUHAMMAD HABIBURRAHMAN', 'gender' => 'L', 'class' => 'XI DKV 2'],
            ['nis' => '20763', 'name' => 'MUHAMMAD NAJIB', 'gender' => 'L', 'class' => 'XI DKV 2'],
            ['nis' => '20767', 'name' => 'MUHAMMAD ZAIDANE AL GHANI', 'gender' => 'L', 'class' => 'XI DKV 2'],
            ['nis' => '20776', 'name' => 'NAILI JULIYANTI', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20784', 'name' => 'NAURA KENES CAHAYA IRLAS', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20786', 'name' => 'NAYLA AZIRINI', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20790', 'name' => 'NAZWA ZAFIRAH', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20792', 'name' => 'NIHLAH AULIA', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20793', 'name' => 'NIKITA PUTRI IHSANA', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20818', 'name' => 'RASYIFAH AULIA RAMADHANI', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20844', 'name' => 'SATYA WIRAYUDHA ARDHANA', 'gender' => 'L', 'class' => 'XI DKV 2'],
            ['nis' => '20861', 'name' => 'SYAFA AWALIYAH', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20878', 'name' => 'YOHANES PRIYANTO', 'gender' => 'L', 'class' => 'XI DKV 2'],
            ['nis' => '20886', 'name' => 'ZASKIA KHAERUNISA', 'gender' => 'P', 'class' => 'XI DKV 2'],
            ['nis' => '20889', 'name' => 'ZILDAN AKBAR MUHANTO', 'gender' => 'L', 'class' => 'XI DKV 2'],
            ['nis' => '20582', 'name' => 'ALIYYA ISLAMIA', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20584', 'name' => 'ALMIRA RIZKI FATHIA', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20595', 'name' => 'ANJA SABILIL HUDA', 'gender' => 'L', 'class' => 'XI AN'],
            ['nis' => '20596', 'name' => 'ANNAMARIA BERNADETTA RAHAYAAN', 'gender' => 'L', 'class' => 'XI AN'],
            ['nis' => '20597', 'name' => 'AQILA ANGGRELIA PUTRI', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20606', 'name' => 'AURA PRATIWI', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20612', 'name' => 'AZKIA NAMAIRA BILQIS', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20615', 'name' => 'AZRA UMAYYA', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20618', 'name' => 'BILLQIS AULIA RASSYIDA', 'gender' => 'L', 'class' => 'XI AN'],
            ['nis' => '20620', 'name' => 'BINTANG BECK\'S JULIANDRO', 'gender' => 'L', 'class' => 'XI AN'],
            ['nis' => '20622', 'name' => 'BYA KANAYA PURNAMA', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20638', 'name' => 'DEVINA SEKAR PUSPITA SARI', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20646', 'name' => 'ELISHIA ZAVIN QURANI', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20649', 'name' => 'FADHIL KHAIRUL ANAM', 'gender' => 'L', 'class' => 'XI AN'],
            ['nis' => '20652', 'name' => 'FAISHAL RADHIANSYAH', 'gender' => 'L', 'class' => 'XI AN'],
            ['nis' => '20673', 'name' => 'GWEEN AQEELA', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20683', 'name' => 'HAYFA ARETHA ZIZI', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20685', 'name' => 'IIM FIRAMIDA ADIYUTA', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20693', 'name' => 'JULIA ANGGRAINI', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20704', 'name' => 'KHAIRUNNISA RAMADHANI', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20708', 'name' => 'KINAR SYAHRANI', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20709', 'name' => 'KITTY CARISYA ZAMZARI', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20722', 'name' => 'MARSHA CAHYANING TYAS', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20738', 'name' => 'MUHAMAD IBNA NURFAUZI', 'gender' => 'L', 'class' => 'XI AN'],
            ['nis' => '20753', 'name' => 'MUHAMMAD DZAKWAN TSAQIF', 'gender' => 'L', 'class' => 'XI AN'],
            ['nis' => '20762', 'name' => 'MUHAMMAD HAIKAL FARIZZI', 'gender' => 'L', 'class' => 'XI AN'],
            ['nis' => '20764', 'name' => 'MUHAMMAD RADHIT FAUZAN', 'gender' => 'L', 'class' => 'XI AN'],
            ['nis' => '20769', 'name' => 'MUHAMMAD ZAKY ARSYAH', 'gender' => 'L', 'class' => 'XI AN'],
            ['nis' => '20780', 'name' => 'NARAUDDAN SYAH PUTRA', 'gender' => 'L', 'class' => 'XI AN'],
            ['nis' => '20781', 'name' => 'NARAYYA BUMI AUDI', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20801', 'name' => 'PUTRI SHABRINA NARASRAYA', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20832', 'name' => 'ROBBANI YUSUF SYAHPUTRA', 'gender' => 'L', 'class' => 'XI AN'],
            ['nis' => '20839', 'name' => 'SALMA ANJANI ADJI', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20849', 'name' => 'SHAFFA ZHAFIRA', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20866', 'name' => 'SYIFA ANANDA FAUZI', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20887', 'name' => 'ZERLINA RARA NATHANIA', 'gender' => 'P', 'class' => 'XI AN'],
            ['nis' => '20589', 'name' => 'ANANDA AHMAD JUNIOR', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20608', 'name' => 'AURELLIA EIRA ZULAIKA', 'gender' => 'P', 'class' => 'XI RPL'],
            ['nis' => '20617', 'name' => 'BAYU HAIKI KAYZAN', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20635', 'name' => 'DEFIN ALFARO QEIS FADILLAH', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20651', 'name' => 'FAIHA FARRAS FADLIAND', 'gender' => 'P', 'class' => 'XI RPL'],
            ['nis' => '20661', 'name' => 'FAUZUNNAJAH ATTAMAM', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20667', 'name' => 'GALIH CRISTIAN HIDAYAT', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20668', 'name' => 'GHIFRAN JULY PRANATA', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20669', 'name' => 'GILANG FIRMANSYAH', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20700', 'name' => 'KENWARD YOGASWARA', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20719', 'name' => 'MALIQI ADITYA AKBAR ATMOKO', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20724', 'name' => 'MARSYAIDINNA NATHIVA BUDIMAN', 'gender' => 'P', 'class' => 'XI RPL'],
            ['nis' => '20736', 'name' => 'MUHAMAD AZAM ALFARIZ', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20739', 'name' => 'MUHAMAD JUNDI AL HAFIDZ', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20742', 'name' => 'MUHAMAD SALIM UMAR', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20743', 'name' => 'MUHAMMAD AHDAN', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20747', 'name' => 'MUHAMMAD AQIL', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20748', 'name' => 'MUHAMMAD ASEP AWALUDIN', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20750', 'name' => 'MUHAMMAD ATTAYA ARDHANA', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20760', 'name' => 'MUHAMMAD GERRAD OKTOVIARIE', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20773', 'name' => 'NABHAN ALMA ARKANA', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20778', 'name' => 'NAJIBA AQILA ZAMA', 'gender' => 'P', 'class' => 'XI RPL'],
            ['nis' => '20788', 'name' => 'NAZRIL ILHAM', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20796', 'name' => 'NUR AZIZAH', 'gender' => 'P', 'class' => 'XI RPL'],
            ['nis' => '20807', 'name' => 'RADINKA ANUNG BRAMANTYO', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20809', 'name' => 'RAFA FARASSY SYANDANA ANDIMI', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20812', 'name' => 'RAISHA BIMA SAPUTRA', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20817', 'name' => 'RASYAD GHANI FATHAN', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20821', 'name' => 'RAYEN HAFIZH MAHESA', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20827', 'name' => 'RIDHO REZKY ANWAR', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20828', 'name' => 'RIDHO SANJAYA', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20833', 'name' => 'RUBYAN ACHBAR SAPUTRA', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20858', 'name' => 'SULTAN DOVEN HAGI', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20871', 'name' => 'VINCENT ADITYA', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20873', 'name' => 'WILDAN HAIBATUR ROHIM', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20885', 'name' => 'ZARIEL WALEED HIDAYAT', 'gender' => 'L', 'class' => 'XI RPL'],
            ['nis' => '20250', 'name' => 'AILSYA ALMAQHFIRA', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20253', 'name' => 'AISYAH RAHMAHAYU', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20256', 'name' => 'ALIF AL FARISI', 'gender' => 'L', 'class' => 'XII MP'],
            ['nis' => '20262', 'name' => 'ALYA MAULIDA HASANAH', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20265', 'name' => 'AMELIA PUTRI', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20267', 'name' => 'ANDINA RAHMAWATI', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20268', 'name' => 'ANDINI WAHYU MARDIANI', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20269', 'name' => 'ANDIRA RAISYA PUTERI', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20273', 'name' => 'ANISA KEYLA LUMI', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20288', 'name' => 'AUREL ANTONIA KOLO', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20289', 'name' => 'AYU KESYA SETIYANA', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20297', 'name' => 'BELLA ANGGRAINI', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20314', 'name' => 'DESY DWI ASTUTI', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20322', 'name' => 'EKA FAJRAH DEWI AGUSTINA', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20346', 'name' => 'GISHEILLA EMMA', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20563', 'name' => 'HAFWEN RASE JIANISLAMY', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20358', 'name' => 'INDAH PUSPITA SARI', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20368', 'name' => 'KAYLA AL FAJRYN', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20370', 'name' => 'KEISHA AZZARIA SYIFA', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20389', 'name' => 'MEYSYITA HUMAYROH', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20425', 'name' => 'MUHAMMAD SYAFWAN ALI YAZID', 'gender' => 'L', 'class' => 'XII MP'],
            ['nis' => '20431', 'name' => 'NABILA OCTAVIA', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20433', 'name' => 'NABILLA TIARA RATIH', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20437', 'name' => 'NADIA NUR FAJRINA', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20460', 'name' => 'PUTRI AYU SAHFITRI', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20478', 'name' => 'REVALIA MAULIDINA', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20481', 'name' => 'REYSYA NADYA PUTRI', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20494', 'name' => 'SABRINA', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20502', 'name' => 'SALMIZYA AZZAHRA', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20513', 'name' => 'SHERIL CAROLINE LANGITAN', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20519', 'name' => 'SITI DINAR', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20526', 'name' => 'SYAFA KHAIRUNISYA', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20527', 'name' => 'SYAFIRA KHOERUNNISSA', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20536', 'name' => 'TANIA SYAFIYYARANI', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20544', 'name' => 'VIKA AOLYA PUTRI SANJAYA', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20555', 'name' => 'ZETA ZERLINDA PURWANTI', 'gender' => 'P', 'class' => 'XII MP'],
            ['nis' => '20242', 'name' => 'ADHWAA ADZRA AULIA ADHAFERA ANANTORI', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20251', 'name' => 'AISYAH ALIVIA KIRANI', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20254', 'name' => 'ALFATH ZAMZAMI NUGRAHA', 'gender' => 'L', 'class' => 'XII AK 1'],
            ['nis' => '20260', 'name' => 'ALISYA TRIANA SAFITRI', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20263', 'name' => 'ALYA NUR\'REYFAH', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20266', 'name' => 'ANATASYA PUTRI WALIDAYAT', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20282', 'name' => 'ARVI KHANIA RHADISTY', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20285', 'name' => 'ATIQAH NADIF ALAMSYAH', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20287', 'name' => 'AURA FITRI ANDINI', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20300', 'name' => 'BONNIETA TRI ANGGRAENI', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20302', 'name' => 'CALISTA GINA MAQVIRA', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20303', 'name' => 'CARISSA VEBRILIA PUTRI', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20333', 'name' => 'FAKHRI NOVRIANSYAH LUBIS', 'gender' => 'L', 'class' => 'XII AK 1'],
            ['nis' => '20341', 'name' => 'FINA NAILATUL IZZA', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20343', 'name' => 'FITRI ROHBIATUL ADAWIYA', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20401', 'name' => 'MUHAMMAD AZMI AR ROHIM', 'gender' => 'L', 'class' => 'XII AK 1'],
            ['nis' => '20387', 'name' => 'MAULA AMALIA', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20388', 'name' => 'MEISY PUTRI CRISTAL', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20412', 'name' => 'MUHAMMAD FATHONI', 'gender' => 'L', 'class' => 'XII AK 1'],
            ['nis' => '20417', 'name' => 'MUHAMMAD IRSYAD ARRASYID', 'gender' => 'L', 'class' => 'XII AK 1'],
            ['nis' => '20447', 'name' => 'NAYLA DWI APRILIA', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20456', 'name' => 'NOVIA FAUZIAH', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20464', 'name' => 'PUTRIANA AMBARWATI', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20468', 'name' => 'RAISSA TALITHA SAKHI', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20474', 'name' => 'RASKIA ADYARISKA', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20482', 'name' => 'REZIKA DWI PRATIWI', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20484', 'name' => 'RIANTI ADIFTA', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20511', 'name' => 'SHECA ZULIA ANASTHACYA', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20523', 'name' => 'SITI NUR HANANNIA ALI', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20524', 'name' => 'SITI NUR HANANTA ALI', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20531', 'name' => 'SYARIFA ARZHA ZEVA', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20532', 'name' => 'SYIFA DWI YAZIKRA', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20542', 'name' => 'VELITA NUR CAHYANI', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20546', 'name' => 'WAHYU KHARISMATULLOH', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20549', 'name' => 'YURI FADHILA RAHMA', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20551', 'name' => 'ZAHRA AYATUL HUSNA', 'gender' => 'P', 'class' => 'XII AK 1'],
            ['nis' => '20238', 'name' => 'ABIDAH SYATHIRA', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20241', 'name' => 'ADESTA PUTRI IRAWAN', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20243', 'name' => 'ADINDA KAYLA SALSABILA', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20272', 'name' => 'ANINDYA CANDANI CANDRANINGTYAS', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20274', 'name' => 'ANISA MEIDINA ARUMI', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20275', 'name' => 'ANISA SEPTIANI', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20276', 'name' => 'ANNISA DWI CAHYATI', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20279', 'name' => 'ARIEL RAMADHAN HIDAYAT', 'gender' => 'L', 'class' => 'XII AK 2'],
            ['nis' => '20283', 'name' => 'ASHYA AMANDA DESTIA', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20305', 'name' => 'CHOIRUN NISA', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20312', 'name' => 'DESFITRI FHELIA NATASYA', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20317', 'name' => 'DINA SAKINAH', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20323', 'name' => 'EKA FITRI HIDAYAH', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20325', 'name' => 'ENGGAR LESTARI ADIYUTA', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20351', 'name' => 'HANIFATUR ROSYIDAH', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20362', 'name' => 'JASMINE AULIA PUTRI RAMADHANI', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20376', 'name' => 'KHALIZA AZZAHRA', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20564', 'name' => 'MUHAMMAD ERLINGGA FADILAH', 'gender' => 'L', 'class' => 'XII AK 2'],
            ['nis' => '20411', 'name' => 'MUHAMMAD FARHAN FEBRIANTO', 'gender' => 'L', 'class' => 'XII AK 2'],
            ['nis' => '20394', 'name' => 'MUHAMAD SURYA PURNOMO', 'gender' => 'L', 'class' => 'XII AK 2'],
            ['nis' => '20451', 'name' => 'NAZWA PUTRI ANGGRAENY', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20452', 'name' => 'NESHIA NAYARA ALIFAH', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20453', 'name' => 'NEYRA AZALYA BILQISH', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20454', 'name' => 'NILA NUR FATIMAH ZAHARA ROLISMAN', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20455', 'name' => 'NINDI AULIA PERTIWI', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20471', 'name' => 'RAISYA RAMADHANI AZZAHRA', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20473', 'name' => 'RARA PUTRI AMELIA', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20489', 'name' => 'RIZKAYLA MAHARANI', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20499', 'name' => 'SABRINA RAHMA INNAYAH', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20506', 'name' => 'SEAN ULTANN VAL QAIS', 'gender' => 'L', 'class' => 'XII AK 2'],
            ['nis' => '20514', 'name' => 'SHERINA SALSABILA', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20516', 'name' => 'SHIERLYN ACI WIDIASTUTI', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20535', 'name' => 'TANIA ANNISA RAHMA', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20537', 'name' => 'TAUFAN SURYA SAFA AL ZENA', 'gender' => 'L', 'class' => 'XII AK 2'],
            ['nis' => '20541', 'name' => 'VANNESA EMANNUELA', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20554', 'name' => 'ZAZKIA BILQISH WIJAYA', 'gender' => 'P', 'class' => 'XII AK 2'],
            ['nis' => '20258', 'name' => 'ALIFAH ALFIH KAMILA', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20270', 'name' => 'ANGGI RAHMADANI', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20307', 'name' => 'DAFFA ABDIL GHANI MUZHAFIR', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20311', 'name' => 'DERRYL RIZKY ALFATHAN', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20318', 'name' => 'DINAR DEWITA NUGROHO', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20328', 'name' => 'FACHRY ZAIDAN RIZAL', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20338', 'name' => 'FEBRIA NUR KHOLISOH', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20339', 'name' => 'FELITA KIARA PRIONO', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20344', 'name' => 'GEMMA PUTRA YOAS', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20353', 'name' => 'HUSNI MUBAROK', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20371', 'name' => 'KENZIE MAHIJA IRAWAN', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20374', 'name' => 'KHADEEJA ATHALLA TAMIDZI', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20380', 'name' => 'LAURA MUTA\' ALIYANSYAH', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20382', 'name' => 'LUTHFI KHAIRUL AZZAM', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20383', 'name' => 'M. DIFO PRASTYO', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20384', 'name' => 'MANGGALA ZURIEL', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20404', 'name' => 'MUHAMMAD CHESTA AL GHAZALI', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20409', 'name' => 'MUHAMMAD FAHRI ABDUL RAHMAN', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20410', 'name' => 'MUHAMMAD  FARREL RIZKY WIBOWO', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20565', 'name' => 'MUHAMMAD RAFIF TAMAM ASYHARI', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20424', 'name' => 'MUHAMMAD RIZKY ILYAS', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20426', 'name' => 'MUHAMMAD SYAMIL RIZKY', 'gender' => 'L', 'class' => 'XII BR 1'],
            ['nis' => '20430', 'name' => 'MUTIARA AUDYAH ACHMAD', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20434', 'name' => 'NADHIFA KHALIS RISWANTO', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20439', 'name' => 'NADILA SHAFIRA LATIF', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20442', 'name' => 'NAILAH SYARIFAH', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20446', 'name' => 'NAY SIFA HAIRUNISA', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20448', 'name' => 'NAYSILA PUTRI SHAKILA', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20457', 'name' => 'NOVIA KHOIRUN NISA', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20459', 'name' => 'NURUL SHABRINA', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20462', 'name' => 'PUTRI MAULIDIYAH ZAHRA', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20508', 'name' => 'SEKAR VERLITA', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20533', 'name' => 'SYIFA HAURA NAILAH', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20538', 'name' => 'TIARA MALYKA RAMADHANI', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20545', 'name' => 'VIONA ROSE PANJAITAN', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20547', 'name' => 'WAHYU TRI ASTUTI', 'gender' => 'P', 'class' => 'XII BR 1'],
            ['nis' => '20255', 'name' => 'ALGYA TRIZA KIRANA', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20257', 'name' => 'ALIFAH ALFAH KAMALA', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20271', 'name' => 'ANGGIA PEBRIANTI', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20278', 'name' => 'ARETI DWI FEBRIYATI', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20280', 'name' => 'ARSYI RABBANI', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20284', 'name' => 'ATHALLAH FAWWAZGHALY RAMADHANA', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20294', 'name' => 'AZRIL RAFA ALFARABI', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20295', 'name' => 'AZZAHRA ALMAGHVIRA', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20299', 'name' => 'BINTANG MAHESA ARUMANJANI', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20310', 'name' => 'DENNIS RHADITYA SUSANTO', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20332', 'name' => 'FAIZ ATTARSYAH', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20342', 'name' => 'FIRDAUS', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20350', 'name' => 'HANA AISH SALMA', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20359', 'name' => 'IQSA RISGIANTI', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20381', 'name' => 'LAZISWA DWI OKTAVIA', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20392', 'name' => 'MOHAMMAD REVO SYAPUTRA RUDIANSYAH', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20399', 'name' => 'MUHAMMAD ANDHIKA', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20400', 'name' => 'MUHAMMAD ASKA RIYAN PRATAMA', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20413', 'name' => 'MUHAMMAD FERY ARDIAN', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20418', 'name' => 'MUHAMMAD NIZAR PRATAMA', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20427', 'name' => 'MUHAMMAD  UMAR  SYAKIEB', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20438', 'name' => 'NADIA SYAHILA PUTRI', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20443', 'name' => 'NAINA AZZAHRA', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20450', 'name' => 'NAZLAA KARIMAH', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20461', 'name' => 'PUTRI AZZAHRANI ALI', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20488', 'name' => 'RISTA AMALIA SUDRAJAT', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20490', 'name' => 'RIZKI RAMADHANI', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20495', 'name' => 'SABRINA ADELIA', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20503', 'name' => 'SALSA KATERINNA', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20507', 'name' => 'SEASHA AFRIYANTI', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20510', 'name' => 'SHAFIRA NURUL AFIAH', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20521', 'name' => 'SITI MAULIDIA', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20529', 'name' => 'SYAINA NURAUNI', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20553', 'name' => 'ZAHRATUSSYITA', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20557', 'name' => 'ZIZA NATZRA DARMAWAN', 'gender' => 'P', 'class' => 'XII BR 2'],
            ['nis' => '20558', 'name' => 'ZOEKEYZA AGHA', 'gender' => 'L', 'class' => 'XII BR 2'],
            ['nis' => '20245', 'name' => 'ADYARAKHA FAEYZA DALIMOENTE', 'gender' => 'L', 'class' => 'XII DKV 1'],
            ['nis' => '20246', 'name' => 'AGHA AQEELA ADININGRAT', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20247', 'name' => 'AGUNG NUGROHO HERYANTO', 'gender' => 'L', 'class' => 'XII DKV 1'],
            ['nis' => '20249', 'name' => 'AHMAD WUSTHO AWALY', 'gender' => 'L', 'class' => 'XII DKV 1'],
            ['nis' => '20566', 'name' => 'AISYAH SHAFA CAMEELA', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20252', 'name' => 'AISYAH KIRANIA PUTRI', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20259', 'name' => 'ALIKA SYIFA FEBRIANA', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20261', 'name' => 'ALVIRA ZASKIA ANJANI', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20264', 'name' => 'AMANDA SHAFIRA', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20281', 'name' => 'ARUMI ZAKIYAH', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20293', 'name' => 'AZLI AKRAM ZIYAD (DIS)', 'gender' => 'L', 'class' => 'XII DKV 1'],
            ['nis' => '20298', 'name' => 'BINTANG CALISTA FEBYOLA', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20301', 'name' => 'CAITLIN RATU CARISSA RUSAD', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20304', 'name' => 'CHERYN ALITHEA NAULI', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20313', 'name' => 'DESWITA ANUGRAH SUSANTI', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20316', 'name' => 'DIANDRA PUTRI TAMALIZA', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20329', 'name' => 'FADHIL RIZKY RAMADHAN', 'gender' => 'L', 'class' => 'XII DKV 1'],
            ['nis' => '20331', 'name' => 'FAHRI ADINATA', 'gender' => 'L', 'class' => 'XII DKV 1'],
            ['nis' => '20336', 'name' => 'FATIH RIZKI SAPUTRA ANWAR', 'gender' => 'L', 'class' => 'XII DKV 1'],
            ['nis' => '20349', 'name' => 'HALIDA ZIA AZZAHRA', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20364', 'name' => 'JIBRAN MAULANA AHMAD', 'gender' => 'L', 'class' => 'XII DKV 1'],
            ['nis' => '20366', 'name' => 'JOVITA CLARISSA', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20379', 'name' => 'LATISHA AMRONA BERLIAN DE FRETES', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20390', 'name' => 'MIRGA ADILLA AHMAD', 'gender' => 'L', 'class' => 'XII DKV 1'],
            ['nis' => '20397', 'name' => 'MUHAMMAD ALLIYU AKBAR', 'gender' => 'L', 'class' => 'XII DKV 1'],
            ['nis' => '20398', 'name' => 'MUHAMMAD ALWI HADZAMI', 'gender' => 'L', 'class' => 'XII DKV 1'],
            ['nis' => '20405', 'name' => 'MUHAMMAD DAFFA JAWZA', 'gender' => 'L', 'class' => 'XII DKV 1'],
            ['nis' => '20463', 'name' => 'PUTRI NAZMI ADILA', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20469', 'name' => 'RAISYA LINTANG ASIH', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20479', 'name' => 'REVAN MANDA PUTRA', 'gender' => 'L', 'class' => 'XII DKV 1'],
            ['nis' => '20492', 'name' => 'ROSALINAH', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20497', 'name' => 'SABRINA HAYU HAFIDZAH', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20501', 'name' => 'SALMA NADHIFA', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20504', 'name' => 'SALSA NABILLA', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20509', 'name' => 'SEZA AL HUSNA', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20525', 'name' => 'STEFANI FIORENCIRA ARISCAYONA PADMASARI', 'gender' => 'P', 'class' => 'XII DKV 1'],
            ['nis' => '20568', 'name' => 'ABI ALFARIZI HAMDIKA', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20244', 'name' => 'ADITYA SAPUTRA', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20286', 'name' => 'AULIANA PUTRI SYA ADAM', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20290', 'name' => 'AZALEA RAISYA ZAHRA', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20306', 'name' => 'CINDY DWI RACHMADITA', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20319', 'name' => 'DINAR NUR ANISA', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20326', 'name' => 'EVINA AULIA DESTA', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20330', 'name' => 'FAHIRA NUR ALIKA', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20337', 'name' => 'FAUZAN AZHIMA', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20345', 'name' => 'GHAZY PUTRA SYAHREZA', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20347', 'name' => 'GISHELLA ZULFARAYA NAFISAH', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20355', 'name' => 'IBAM FIRDAUS ABDULLAH', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20363', 'name' => 'JAUZA AMIRA FAIRUZ SALMA', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20567', 'name' => 'KEMILAU CAHAYA BINTANG', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20372', 'name' => 'KEYLA ZHEZA PERMATA WIJAYA', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20393', 'name' => 'MUHAMAD FAHRI', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20396', 'name' => 'MUHAMMAD AKMAL FARIDZI', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20402', 'name' => 'MUHAMMAD BENZEMA NURCHASAN', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20406', 'name' => 'MUHAMMAD DAVI', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20421', 'name' => 'MUHAMMAD RAFFI ALHAFIDZ', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20422', 'name' => 'MUHAMMAD RASYAD', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20423', 'name' => 'MUHAMMAD RIFAN GHIFARI', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20432', 'name' => 'NABILA SAFITRI', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20436', 'name' => 'NADIA ATHAYA HAMIDAH', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20440', 'name' => 'NADINE SYANIE AISYAH', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20445', 'name' => 'NASYA SYAKIEB', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20449', 'name' => 'NAZLA FAHIRA AL BAKRI', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20467', 'name' => 'RAIHAN ADITYA PASHA', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20472', 'name' => 'RANDI RAMADHAN PUTRA', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20477', 'name' => 'REHAN PRIHANTONO', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20480', 'name' => 'REVAND AQILLA PRATAMA', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20493', 'name' => 'SABIQ FATAH ABDULLAH AKRAM', 'gender' => 'L', 'class' => 'XII DKV 2'],
            ['nis' => '20517', 'name' => 'SILVIA APRIYANNIS SUNDUS', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20540', 'name' => 'VANESSYA DWI FEBRIYANTI', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20552', 'name' => 'ZAHRA KYLA SALSABILA TRISAN', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20556', 'name' => 'ZHAFIRA NUR SABRINA', 'gender' => 'P', 'class' => 'XII DKV 2'],
            ['nis' => '20239', 'name' => 'ABIGAIL AIRIN', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20292', 'name' => 'AZKA KAMILA EL HAFIDZ BASRI', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20315', 'name' => 'DHIVA VINOLIA PUTRI', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20320', 'name' => 'DWI ADLY NUGROHO', 'gender' => 'L', 'class' => 'XII AN'],
            ['nis' => '20324', 'name' => 'ELSA SALSABIILA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20334', 'name' => 'FATHIA THURFA SYAHIRA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20335', 'name' => 'FATHIYA KEISHA PUTRI SUKMANA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20348', 'name' => 'HAFIZA KHAIRA LUBNA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20354', 'name' => 'HUZAIMAH', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20360', 'name' => 'IZZATUL INAYAH', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20367', 'name' => 'KAISAR AKHTAR KEIHAN SANY', 'gender' => 'L', 'class' => 'XII AN'],
            ['nis' => '20369', 'name' => 'KAYLA AMICAL LIZAHWA UMBAS', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20377', 'name' => 'KHAYYARA ALMAGHFIRA FRADITYA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20378', 'name' => 'LATHIFAH ZOE AGATHA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20385', 'name' => 'MARSHA AULIA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20386', 'name' => 'MARSYA SABRINA AISYAH', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20391', 'name' => 'MODYANA CATANIA BUANA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20414', 'name' => 'MUHAMMAD HANIF RIDWAN', 'gender' => 'L', 'class' => 'XII AN'],
            ['nis' => '20435', 'name' => 'NADHYRA PUTRI ZAHIRA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20441', 'name' => 'NAFA RAMADHANI', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20444', 'name' => 'NANDA CITRA KIRANA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20458', 'name' => 'NUR AMIRAH KAMALIA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20465', 'name' => 'RADHYTIA MIKAILA ROONEY SUSANTO', 'gender' => 'L', 'class' => 'XII AN'],
            ['nis' => '20466', 'name' => 'RADITYA ZAKY RAMADHAN', 'gender' => 'L', 'class' => 'XII AN'],
            ['nis' => '20470', 'name' => 'RAISYA PUTRI RAFAINDRA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20476', 'name' => 'RAZAN AHMAD ALZARI', 'gender' => 'L', 'class' => 'XII AN'],
            ['nis' => '20485', 'name' => 'RIBHAN SHUFY', 'gender' => 'L', 'class' => 'XII AN'],
            ['nis' => '20487', 'name' => 'RINJANI LARYSSA GERNA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20491', 'name' => 'ROBIN', 'gender' => 'L', 'class' => 'XII AN'],
            ['nis' => '20512', 'name' => 'SHENA AULIA', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20518', 'name' => 'SITI ANISAH', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20520', 'name' => 'SITI MARYAM NAIDINA ALI', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20539', 'name' => 'TIRZA RAID SYACHANIF', 'gender' => 'L', 'class' => 'XII AN'],
            ['nis' => '20543', 'name' => 'VERONICA ANGEL', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20548', 'name' => 'WINDI MELINDA PUTRI', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20550', 'name' => 'ZAHRA APRI YANI', 'gender' => 'P', 'class' => 'XII AN'],
            ['nis' => '20240', 'name' => 'ABYAN RAFFADHA', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20891', 'name' => 'ADITHYA RIZKY KARA ARDHANI', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20248', 'name' => 'AGUS JIDDAN PERMANA', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20291', 'name' => 'AZKA FAADILAH ARRAFI', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20296', 'name' => 'AZZAM RAHMAN ALGHANI', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20308', 'name' => 'DAFFA IRAWAN', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20309', 'name' => 'DAFFI ALFIAN HADI', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20321', 'name' => 'DZIKRA SEPTA RAMADHAN', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20327', 'name' => 'FAATIHAH MICHELLY JULIAN', 'gender' => 'P', 'class' => 'XII RPL'],
            ['nis' => '20340', 'name' => 'FIKA ZHAFIRA NASUTION', 'gender' => 'P', 'class' => 'XII RPL'],
            ['nis' => '20352', 'name' => 'HISHON WUTSQO SETYA ASMANDA', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20356', 'name' => 'IBNU ALFIN RISKY MUBAROK', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20357', 'name' => 'IKLIL BADAR', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20361', 'name' => 'IZZUDDIN IKHSAN AL-FAHRIZY', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20365', 'name' => 'JOVIN JOSHAFAT HAMONANGANKU SIREGAR', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20375', 'name' => 'KHALIFAH ISLAMI', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20395', 'name' => 'MUHAMMAD AKHDAN', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20403', 'name' => 'MUHAMMAD BILAL', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20407', 'name' => 'MUHAMMAD DIANSYAH DWI PUTRA', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20415', 'name' => 'MUHAMMAD HARYA NUR ADINATA', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20416', 'name' => 'MUHAMMAD HILAL AL FARIS', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20419', 'name' => 'MUHAMMAD PALESTINE ATITAR', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20420', 'name' => 'MUHAMMAD RAFFA RAFIF NABHAN', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20428', 'name' => 'MUHAMMAD WILDAN', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20429', 'name' => 'MUHAMMAD YUSUF ISBATUL GUSTI', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20475', 'name' => 'RA\'UF ARKAN HABIIBI', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20483', 'name' => 'REZKY ACHMAD', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20486', 'name' => 'RIDHO ADI SYAHPUTRA', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20496', 'name' => 'SABRINA ASMARA MELATI', 'gender' => 'P', 'class' => 'XII RPL'],
            ['nis' => '20498', 'name' => 'SABRINA MARTHA LARASATI', 'gender' => 'P', 'class' => 'XII RPL'],
            ['nis' => '20500', 'name' => 'SADEWA VIRGIAWANSYAH', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20505', 'name' => 'SALWA RAMADHINA ALTHA FUNNISA', 'gender' => 'P', 'class' => 'XII RPL'],
            ['nis' => '20515', 'name' => 'SHEVA ABIYAN SYAKIB', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20528', 'name' => 'SYAFIRA MAULIDA', 'gender' => 'P', 'class' => 'XII RPL'],
            ['nis' => '20530', 'name' => 'SYAMIL GYMNASTIAR NUGROHO', 'gender' => 'L', 'class' => 'XII RPL'],
            ['nis' => '20534', 'name' => 'TALITA AZRA ATAYA', 'gender' => 'P', 'class' => 'XII RPL'],
        ];

        $now = now();
        $records = [];

        foreach ($students as $data) {
            $classId = $classMap[$data['class']] ?? null;

            if (!$classId) {
                $this->command->warn("Kelas [{$data['class']}] tidak ditemukan, siswa [{$data['name']}] dilewati.");
                continue;
            }

            $records[] = [
                'nis'        => $data['nis'],
                'name'       => $data['name'],
                'gender'     => $data['gender'],
                'class_id'   => $classId,
                'password'   => $password,
                'is_active'  => true,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        // Upsert dalam chunk untuk performa optimal
        foreach (array_chunk($records, 100) as $chunk) {
            Student::upsert(
                $chunk,
                ['nis'],
                ['name', 'gender', 'class_id', 'password', 'is_active', 'updated_at']
            );
        }

        $this->command->info('RealStudentsSeeder: ' . count($records) . ' siswa berhasil di-seed ke sistem.');
    }
}
